# Site settings
title: downey.io
name: Tim Downey
description: "Tim Downey's photography blog -- mostly landscapes, sometimes other stuff"
keywords:
  - photography
  - landscape photography
  - photoblog
baseurl: ""
url: "https://photo.downey.io"

# Build settings
highlighter: pygments
paginate: 15
permalink: photos/:year/:month/:day/:title.html

exclude:
  - s3_website.yml
plugins:
  - jekyll-sitemap
  - jekyll-paginate

assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
